name: generar-predicciones

on:
  workflow_dispatch:
    inputs:
      csv_url:
        description: "URL del CSV (19 features). Si vacío, usa el CSV local del repo."
        required: false
        default: ""
  schedule:
    - cron: "0 10,22 * * *"

jobs:
  predict:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write requirements.txt (pinned)
        run: |
          cat > requirements.txt <<'REQ'
          numpy==1.26.4
          pandas==2.1.4
          scikit-learn==1.3.2
          joblib==1.4.2
          tensorflow==2.15.0
          REQ

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt
          python - <<'PY'
          import sys, tensorflow as tf, numpy, pandas
          print("PY:", sys.version)
          print("TF:", tf.__version__)
          print("NP:", numpy.__version__)
          print("PD:", pandas.__version__)
          PY

      - name: Run predict (debug: no aborta el job)
        env:
          CSV_URL: ${{ github.event.inputs.csv_url }}
        run: |
          set -x
          if [ -n "${CSV_URL}" ]; then
            python scripts/predict.py --csv "${CSV_URL}" --out public/predicciones.json || true
          else
            python scripts/predict.py --out public/predicciones.json || true
          fi
          echo "=== Archivos en public/ ==="
          ls -lah public/ || true
          echo "=== Inicio del JSON ==="
          head -c 1200 public/predicciones.json 2>/dev/null || echo "(no se generó JSON)"

      - name: Verify JSON
        run: |
          if [ -s public/predicciones.json ]; then
            echo "OK: JSON generado"
          else
            echo "::error::No se generó public/predicciones.json"
            exit 1
          fi

      - name: Commit predicciones.json
        if: success()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/predicciones.json
          if git commit -m "chore: update predicciones.json"; then
            git push
          else
            echo "No changes to commit."
