name: generar-predicciones

on:
  workflow_dispatch:
    inputs:
      csv_url:
        description: "URL del CSV (19 features). If empty, uses local CSV."
        required: false
        default: ""
  schedule:
    - cron: "0 10,22 * * *"  # twice per day, UTC

jobs:
  predict:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write requirements.txt
        shell: bash
        run: |
          cat > requirements.txt <<'REQ'
          numpy==1.26.4
          pandas==2.1.4
          scikit-learn==1.3.2
          joblib==1.4.2
          tensorflow==2.15.0
          REQ

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        shell: bash
        run: |
          set -euxo pipefail
          python -m pip install -U pip wheel setuptools
          pip install -r requirements.txt
          python - <<'PY'
          import sys, tensorflow as tf, numpy, pandas
          print("PY:", sys.version)
          print("TF:", tf.__version__)
          print("NP:", numpy.__version__)
          print("PD:", pandas.__version__)
          PY

      - name: Run predict (debug)
        shell: bash
        run: |
          set -x
          CSV_URL="${{ github.event.inputs.csv_url }}"
          if [[ -n "$CSV_URL" ]]; then
            python scripts/predict.py --csv "$CSV_URL" --out public/predicciones.json || true
          else
            python scripts/predict.py --out public/predicciones.json || true
          fi
          echo "=== public/ ==="
          ls -lah public/ || true
          echo "=== JSON head ==="
          head -c 1200 public/predicciones.json 2>/dev/null || echo "(no JSON)"

      - name: Verify JSON
        shell: bash
        run: |
          if [[ -s public/predicciones.json ]]; then
            echo "OK: JSON generated"
          else
            echo "::error::public/predicciones.json not generated"
            exit 1
          fi

      - name: Commit JSON
        if: success()
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/predicciones.json
          if git commit -m "chore: update predicciones.json"; then
            git push
          else
            echo "No changes to commit."

