name: generar-predicciones

on:
  workflow_dispatch:
    inputs:
      csv_url:
        description: "URL del CSV (19 features). Si vacío, usa el CSV local del repo."
        required: false
        default: ""
  schedule:
    - cron: "0 10,22 * * *"   # 10:00 y 22:00 UTC

jobs:
  predict:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install deps (pinned + TF)
        shell: bash
        run: |
          set -euxo pipefail
          python -V
          python -m pip install -U pip wheel setuptools

          # 🔒 Versiones compatibles con TF 2.15 (evita conflictos)
          pip install "numpy==1.26.4" "pandas==2.1.4" "scikit-learn==1.3.2" "joblib==1.4.2"
          # Primero intentamos TF CPU. Si el wheel no aparece, probamos `tensorflow` genérico.
          (pip install "tensorflow-cpu==2.15.0") || (pip install "tensorflow==2.15.0")

          python - <<'PY'
          import sys, tensorflow as tf, numpy, pandas
          print("PY:", sys.version)
          print("TF:", tf.__version__)
          print("NP:", numpy.__version__)
          print("PD:", pandas.__version__)
          PY

      - name: Debug repo + CSV
        shell: bash
        env:
          CSV_URL: ${{ github.event.inputs.csv_url }}
        run: |
          set -euxo pipefail
          ls -lah
          echo "CSV_URL='${CSV_URL}'"
          python - <<'PY'
          import glob, pandas as pd, os, json
          cands = ["dataset_trafico_clima_nacional_v2.csv", "*trafico_clima*_v2*.csv"]
          path = None
          for pat in cands:
              g = glob.glob(pat)
              if g: path = g[0]; break
          print("Local CSV:", path)
          if path:
              df = pd.read_csv(path, nrows=3)
              print("Columns:", df.columns.tolist())
              print(df.head())
          PY

      - name: Run predict
        shell: bash
        env:
          CSV_URL: ${{ github.event.inputs.csv_url }}
        run: |
          set -euxo pipefail
          if [ -n "${CSV_URL}" ]; then
            python scripts/predict.py --csv "${CSV_URL}" --out public/predicciones.json
          else
            python scripts/predict.py --out public/predicciones.json
          fi
          ls -lah public/
          head -c 800 public/predicciones.json || true
          echo

      - name: Commit predicciones.json
        shell: bash
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/predicciones.json
          if git commit -m "chore: update predicciones.json"; then
            git push
          else
            echo "No changes to commit."
