      - name: Run predict
        env:
          CSV_URL: ${{ github.event.inputs.csv_url }}
        run: |
          set -euxo pipefail
          if [ -n "${CSV_URL}" ]; then
            python scripts/predict.py --csv "${CSV_URL}" --out public/predicciones.json
          else
            python scripts/predict.py --out public/predicciones.json
          fi
          ls -lah public/ || true
          head -c 800 public/predicciones.json || true

